### ISSUE TITLE
TODO listi fyrir Get requestur

### ISSUE THREAD

**Issue by jaykaytherobot** [jaykaytherobot/vef2-h1#2]
Þetta er allt GET requests:

**/tv** 

- [x]  það þarf að page-a niðurstöðurnar'

**/tv/:id** 

- [x]  virkar ekki, server stallar eftir unhandled promise rejection
- [x]  virkar ekki af annarri ástæðu, skilar alltaf engum þætti
- [x]  það þarf að vera einhver lógík sem finnur, ef notandi er skráður inn => sýndu stöðu sjónvarpsþáttarins

**/tv/:id/season**

- [x]  Þarf að page-a

- [x]  það er eitthvað serie id sem ég veit ekki hvað er

**/tv/:id/season/:id**

- [x]  Virkar ekki, server stallar eftir Cannot read property of 0

**/genres**

- [x]  skilar bara foobar

- [x]  þarf að page-a
