### ISSUE TITLE
TODO listi yfir atriði önnur en GET

### ISSUE THREAD

**Issue by TryggviF** [jaykaytherobot/vef2-h1#3]
**Almennt**
- [ ] Það þarf að XSSa

**/:serieID**
- [x] Vantar PATCH á /:serieID
- [x] Vantar DELETE á /:serieID

**/:serieID/season/:seasonNum**
- [x] Vantar DELETE á /:serieID/season/:seasonNum

**/:serieID/season/:seasonNum/episode**
- [x] Vantar POST á /:serieID/season/:seasonNum/episode
- [ ] Vantar DELETE á /:serieID/season/:seasonNum/episode

**/:serieID/season/:seasonNum/episode/:episodeNum**
- [x] Vantar POST á /:serieID/season/:seasonNum/episode/:episodeNum

Fann ekki fleiri hluti sem svara til "FOO"
